# Generated by Django 2.2.1 on 2019-06-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='mobile',
            field=models.CharField(max_length=200),
        ),
    ]
