# Generated by Django 2.2.1 on 2019-06-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0002_auto_20190614_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otpuser', to='uaccounts.RegisteredUser')),
            ],
        ),
    ]
