# Generated by Django 2.2.1 on 2019-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0006_auto_20190704_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='user_type',
            field=models.CharField(choices=[('1', 'User'), ('2', 'Service Provider')], max_length=20),
        ),
    ]
