# Generated by Django 2.2.1 on 2019-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0007_auto_20190704_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='has_dual_account',
            field=models.BooleanField(default=False),
        ),
    ]
