# Generated by Django 2.2.1 on 2019-06-04 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0001_initial'),
        ('extra', '0003_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unot', to='extra.Notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unuser', to='uaccounts.RegisteredUser')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(through='extra.UserNotification', to='uaccounts.RegisteredUser'),
        ),
    ]
