# Generated by Django 2.2.1 on 2019-06-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_auto_20190604_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
