# Generated by Django 2.2.1 on 2019-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0007_newoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='newoptions',
            name='option_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
