# Generated by Django 2.2.1 on 2019-06-27 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0008_newoptions_option_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='newoptions',
            old_name='option_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
