# Generated by Django 2.2.1 on 2019-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0009_auto_20190627_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
