# Generated by Django 2.2.1 on 2019-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0010_auto_20190627_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='help',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='legal',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
