# Generated by Django 2.2.1 on 2019-06-29 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0011_auto_20190627_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 15, 54, 43, 666514)),
        ),
    ]
