# Generated by Django 2.2.1 on 2019-06-29 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0014_auto_20190629_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
