# Generated by Django 2.2.1 on 2019-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='serviceprovider/offer/image')),
                ('video1', models.FileField(blank=True, null=True, upload_to='serviceprovider/offer/video')),
                ('video2', models.FileField(blank=True, null=True, upload_to='serviceprovider/offer/video')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('coupon', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
