# Generated by Django 2.2.1 on 2019-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0005_auto_20190625_1916'),
        ('offer', '0002_offer_garage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_desc', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('validity_from', models.DateTimeField(auto_now_add=True)),
                ('validity_to', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_plan', to='offer.SubscriptionPlan')),
                ('ruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='us_ruser', to='uaccounts.RegisteredUser')),
            ],
        ),
    ]
