# Generated by Django 2.2.1 on 2019-07-02 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 11, 3, 50, 82646)),
        ),
    ]
