# Generated by Django 2.2.1 on 2019-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_auto_20190702_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
