# Generated by Django 2.2.1 on 2019-07-02 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20190702_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 11, 11, 35, 835346)),
        ),
    ]
