# Generated by Django 2.2.1 on 2019-07-02 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_subscriptionplan_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 11, 12, 34, 57385)),
        ),
    ]
