# Generated by Django 2.2.1 on 2019-07-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20190702_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='validity_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='validity_to',
            field=models.DateField(),
        ),
    ]
