# Generated by Django 2.2.1 on 2019-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0004_auto_20190604_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
