# Generated by Django 2.2.1 on 2019-06-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0006_auto_20190604_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='store_image',
            new_name='store_image1',
        ),
    ]
