# Generated by Django 2.2.1 on 2019-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0007_auto_20190620_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='slug2',
            field=models.SlugField(default=''),
        ),
    ]
