# Generated by Django 2.2.1 on 2019-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0008_auto_20190620_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='slug1',
            field=models.SlugField(default=''),
        ),
    ]
