# Generated by Django 2.2.1 on 2019-06-21 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0011_auto_20190621_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubtype',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
