# Generated by Django 2.2.1 on 2019-06-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0012_servicesubtype_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubtype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
