# Generated by Django 2.2.1 on 2019-07-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uaccounts', '0008_registereduser_has_dual_account'),
        ('saccounts', '0013_auto_20190621_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempGarageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='serviceprovider/temp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgi_user', to='uaccounts.RegisteredUser')),
            ],
        ),
    ]
