# Generated by Django 2.2.1 on 2019-07-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0014_tempgarageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubtype',
            name='subcategory_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='category_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
