# Generated by Django 2.2.1 on 2019-07-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0015_auto_20190709_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
