# Generated by Django 2.2.1 on 2019-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saccounts', '0016_auto_20190710_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
